name: Generate org files

on:
  push:
    paths:
      - "knp/**"

jobs:
  generate-org:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: uv sync
      - name: Generate org files
        run: uv run python scripts/knp_to_org.py
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: update org files
          # Optional glob pattern of files which should be added to the commit
          file_pattern: org/**/*.org
          # Optional. Prevents the shell from expanding filenames.
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: false
