name: Generate requirements.txt

on:
  push:
    paths:
      - "pyproject.toml"
      - "uv.lock"

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
      - name: Export requirements.txt
        run: uv export --no-hashes > requirements.txt
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: update requirements.txt
          # Optional glob pattern of files which should be added to the commit
          file_pattern: requirements.txt
          # Optional. Prevents the shell from expanding filenames.
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
